### ISSUE TITLE
Feature Request: support git worktree (bare)

### ISSUE THREAD

**Issue by linrongbin16** [linrongbin16/gitlinker.nvim#107]
relate: https://github.com/ruifm/gitlinker.nvim/issues/83

**Comment by linrongbin16** [comment]
use `git rev-parse --is-bare-repository` to detect if current repo is a bare repo, see: https://stackoverflow.com/a/1830712/4438921

**Comment by linrongbin16** [comment]
in issue: https://github.com/ruifm/gitlinker.nvim/issues/83, the reporter provide re-produce steps are:

- Do `git clone --bare https://github.com/ruifm/gitlinker.nvim && cd gitlinker.nvim.git && git worktree add main`
- Go to `main` and open a file there, e.g. `README.md`.
- press `<leader>gy` (default mapping). The error Failed to get closest revision in that exists in remote 'origin' should appear.


In this step, the `gitlinker.nvim/.git/config` file is:

```
[core]
	repositoryformatversion = 0
	filemode = false
	bare = true
	symlinks = false
	ignorecase = true
[remote "origin"]
	url = https://github.com/ruifm/gitlinker.nvim
```

But when I add the `fetch` in the last line:

```
[core]
	repositoryformatversion = 0
	filemode = false
	bare = true
	symlinks = false
	ignorecase = true
[remote "origin"]
	url = https://github.com/ruifm/gitlinker.nvim
	fetch = +refs/heads/*:refs/remotes/origin/*
```

And run `git fetch`, it will work, so it's a git config issue, not a plugin issue actually.

**Comment by linrongbin16** [comment]
Maybe the optimization is to detect whether there's a `fetch` configured in `.git/config`, and suggest user to check whether has the correct git config.

**Comment by linrongbin16** [comment]
fixed in #143

**Comment by hqkhan** [comment]
Hello, wanted to ask if there's an example of working with bare repo for gitlinker. I wasn't sure how to get it to work with gitlinker.

**Comment by linrongbin16** [comment]
hi @hqkhan , it should work out of box. You should not need config.

**Comment by jearbear** [comment]
Sorry to dig this up again, but I was working if this is supposed to work for my use case.

I have my dotfiles scattered throughout my home directory and use a bare git repo to manage them. So I have a `~/.dotfiles` directory that contains a bare git repo and the `config` file in the directory has the following contents:
```
[core]
	repositoryformatversion = 0
	filemode = true
	bare = true
	ignorecase = true
	precomposeunicode = true
[remote "origin"]
	url = git@github.com:jearbear/dotfiles.git
    fetch = +refs/heads/*:refs/remotes/origin/*
```

If I try to use Gitlink on a file in the repo such as `~/.config/nvim/lua/plugins.lua`, I will get the following error: `[gitlinker] fatal: not a git repository (or any of the parent directories): .git`. Is this expected?

**Comment by linrongbin16** [comment]
hi @jearbear,

this looks like a new case I haven't met before. 

Could you help provide more reproduce steps? It will be much easier if I know how to git clone your repo, and I could reproduce this issue in my local machine, and help me figure out a solution

**Comment by hqkhan** [comment]
Apologies on the late reply from my end. 

I have a repo sitting in `~/.cfg`. The worktree is `$HOME`. I have an alias that I use to interact with this repo:
```
alias dot='git -c status.showUntrackedFiles=no --git-dir=$HOME/.cfg/ --work-tree=$HOME -C ${HOME}'
```

When I tried using gitlinker, I got the following error:
```
[gitlinker] fatal: this operation must be run in a work tree
```

**Comment by linrongbin16** [comment]
hi @hqkhan , could you share the `.git/config` file in the `$HOME/.cfg` git dir?

**Comment by linrongbin16** [comment]
hi @hqkhan ,

Sorry for being late, but I still don't know how to reproduce this issue.

Would you please help me with either one of below options:
- If your git repositories are public in github, could you give me some bash commands such as `git clone xxxx $HOME/.cfg && cd $HOME/.cfg && nvim {FILENAME}` so I could reproduce this issue.
- Or you could clone this plugin to your local machine, and set it to debug mode, then view the debug loggings in your local machine.

**Comment by linrongbin16** [comment]
I will close this ticket for now, since it's not updated for a long time.
