### ISSUE TITLE
Feature Request: Provide an option for line markers customization

### ISSUE THREAD

**Issue by skoch13** [linrongbin16/gitlinker.nvim#114]
Sorry, but I have to cross-post this: https://github.com/linrongbin16/gitlinker.nvim/discussions/65#discussion-5429838

Is there any option to achieve it?

**Comment by linrongbin16** [comment]
hi @skoch13 , I am trying to implement the `#lines-1:16` for bitbucket.org in PR: https://github.com/linrongbin16/gitlinker.nvim/pull/113.

It seems quite close to your requirements, while you need the `?lines-1`, would you help provide the format of line ranges? is it `?lines-1:16` or something else?

**Comment by skoch13** [comment]
@linrongbin16 thank you for your reply. The range is formed as follows: `&line=1&lines-count=2`

**Comment by linrongbin16** [comment]
emmmmm, if it's a private/personal git host, I think I will just give you a simple code snippet to support.

once the PR https://github.com/linrongbin16/gitlinker.nvim/pull/113 is merged, you could use:


```lua
require('gitlinker').setup({
  mapping = {
    ["<leader>gl"] = {
      action = require("gitlinker.actions").clipboard,
      desc = "Copy git link to clipboard",
      router = function(lk) 
        -- @param range {lstart:integer,lend:integer}
        local function your_lines(range)
          if type(range) ~= 'table' or type(range.lstart) ~= 'number' then
            return nil
          end
          local tmp = string.format([[&lines=%d]], range.lstart)
          if type(range.lend) == "number" and range.lend > range.lstart then
            tmp = tmp .. string.format([[&lines-count=%d]], r.lend)
          end
          return tmp
        end
        local builder = require('gitlinker.routers').Builder:new(lk, your_lines)
        return builder:build("blob")
      end,
    },
  },
})
```

Please referece this code: https://github.com/linrongbin16/gitlinker.nvim/blob/a371afba77d0832926ba701c76424f8e5fb68b52/lua/gitlinker/routers.lua#L97

**Comment by skoch13** [comment]
@linrongbin16 I could not ask for more 😀

**Comment by linrongbin16** [comment]
hi @skoch13, the pr is merged into master branch, please pull latest and try it.

**Comment by linrongbin16** [comment]
hi @skoch13 , since this PR https://github.com/linrongbin16/gitlinker.nvim/pull/118, you will probably configure for your self-host git hosts, you can configure the `router_binding` here:

https://github.com/linrongbin16/gitlinker.nvim/blob/c5ecd1983b8897637ced89748b90ae3c556df3c9/README.md?plain=1#L302-L323

**Comment by skoch13** [comment]
@linrongbin16 thank you for the detailed reply. One more clarification: will the default say github repos behavior be preserved?

**Comment by linrongbin16** [comment]
hi @skoch13 , I add `router_binding` option yesterday, so it's true that the previous config I shared with you, will actually override the default `github` `gitlab` routers.

but now in latest master branch, you can use below config:

```lua
-- @param range {lstart:integer,lend:integer}
local function your_lines(range)
  if type(range) ~= 'table' or type(range.lstart) ~= 'number' then
    return nil
  end
  local tmp = string.format([[&lines=%d]], range.lstart)
  if type(range.lend) == "number" and range.lend > range.lstart then
    tmp = tmp .. string.format([[&lines-count=%d]], r.lend)
  end
  return tmp
end

require('gitlinker').setup({
  router_binding = {
    browse = {
      ["^github%.your%.host"] = function(lk)
        local builder = require('gitlinker.routers').Builder:new(lk, your_lines)
        return builder:build("blob")
      end,
    },
  },
})
```

also please note the `Builder` is an internal build string helper class, there's no guarantee the class signature is stable (but you can use it for now).

**Comment by skoch13** [comment]
> but please rename router_binding to router since https://github.com/linrongbin16/gitlinker.nvim/pull/120 been merged into master.

Already did, but now I have deprecation warning for `mapping`, while I don't use it explicitly.

**Comment by linrongbin16** [comment]
please set `mapping=false`, it will be removed.

**Comment by skoch13** [comment]
The parser fails with the following. It might be that linker.lua cannot parse the following structure:
`ssh://git@git.xxx.xxx/PROJECT_KEY/PROJECT.git`

![Screenshot2023-11-16 at 23 21 35](https://github.com/linrongbin16/gitlinker.nvim/assets/29177689/c65d68cd-4f3a-41ea-8c33-6eefc11bf8d7)

**Comment by linrongbin16** [comment]
hi @skoch13, protocol `ssh://git@` is not been correctly parsed, I think it's still belong to `git` protocol?

**Comment by skoch13** [comment]
@linrongbin16 ssh is the most common for self-hosted solutions. When I used the previous version of your plugin the mapping was the following:

```
              ["^ssh://git@git%.xxx%.yyy/([_%.%-%w]+)/([_%.%-%w]+)%.git$"] = "https://xxx.yyy/p/%1/repositories/%2/files/",
              ["^https?://git%.xxx%.yyy/([_%.%-%w]+)/([_%.%-%w]+)%.git$"] = "https://xxx.yyy/p/%1/repositories/%2/files/",

```

**Comment by linrongbin16** [comment]
I feel like the `router` should match both protocol+host, current design is not  generic enough

**Comment by linrongbin16** [comment]
hi @skoch13 , I merged #124 and #126  into master branch, should fix your issue now. please have a try.

and thanks for provide so many use cases, they're important to make this plugin real good.

**Comment by skoch13** [comment]
I'm glad to help! I must admit, you're very responsive and eager to make this project even better. 😄 Template strings are awesome!

Unfortunately, linker now fails on line [65](https://github.com/linrongbin16/gitlinker.nvim/blob/f2db69f8f324ca4136380d9f8de9e5ac2b02ef5e/lua/gitlinker/linker.lua#L65), while the remote url remains the same `ssh://git@git.xxx.yyy/PROJECT_KEY/PROJECT.git`

**Comment by linrongbin16** [comment]
@skoch13 , oh it's another use case, I will fix it.

**Comment by skoch13** [comment]
@linrongbin16 it works! thank you!

two things two mention:

* `?` question mark is required for query string
*  (I don't think this requires any fixes): to achieve the desired line range selection I have to use the following construction with + 1

```
 .. "?&line={_A.LSTART}"
 .. "{_A.LEND > _A.LSTART and ('&lines-count=' .. _A.LEND - _A.LSTART + 1) or ''}",
```

**Comment by linrongbin16** [comment]
> @linrongbin16 it works! thank you!
> 
> two things two mention:
> 
> * `?` question mark is required for query string
> * (I don't think this requires any fixes): to achieve the desired line range selection I have to use the following construction with + 1
> 
> ```
>  .. "?&line={_A.LSTART}"
>  .. "{_A.LEND > _A.LSTART and ('&lines-count=' .. _A.LEND - _A.LSTART + 1) or ''}",
> ```

thanks for point out, I will update readme.

close this issue now.

**Comment by linrongbin16** [comment]
> I'm glad to help! I must admit, you're very responsive and eager to make this project even better. 😄 Template strings are awesome!


Thank you, I just feel it's interesting to solve these kind of issues (even it's a little tired to work on it).

This plugin's scenario is much more complicated than I had thought at the beginning. And I really enjoy to do it with the best solution I've found.
