### ISSUE TITLE
Support sourcecode display for other rendered documents

### ISSUE THREAD

**Issue by bagnaram** [linrongbin16/gitlinker.nvim#142]
Currently only `.md` files are handled for sourcecode display mode. Adding support for other formats like `.adoc` or `.org`.

Also the ability to use `?display=source` on forge-specific routes.

**Comment by linrongbin16** [comment]
> Currently only `.md` files are handled for sourcecode display mode. Adding support for other formats like `.adoc` or `.org`.
> 
> Also the ability to use `?display=source` on forge-specific routes.

do you mean for `github.com`, also add `?plain=1` for `.adoc`, `.org` files?

can you give an example about the forge-specific hosts?

**Comment by linrongbin16** [comment]
I feel like adding `?plain=1` for all files without detect the file type is a simple but working solution. the `?plain=1` don't affected browser to open it.

**Comment by bagnaram** [comment]
Yes that should be able to work. The only problem with this approach is that it is forge-specific. For example, `codeberg.org` uses `?display=source` for its page.

**Comment by linrongbin16** [comment]
> Yes that should be able to work. The only problem with this approach is that it is forge-specific. For example, `codeberg.org` uses `?display=source` for its page.

got it, for different git hosts (github, codeberg, etc), will use different implementations.

**Comment by linrongbin16** [comment]
I close this issue now.
