### ISSUE TITLE
Builtin ability to copy/open url of main/master branch

### ISSUE THREAD

**Issue by dlvhdr** [linrongbin16/gitlinker.nvim#151]
Hi! Thanks for maintaining this.
I would like to copy/open the url with the rev set as the main branch.
I figure it would be possible to do with routers, but I think the more user friendly approach will be to have a builtin command.

The logic we'll be handling for users is figuring out the name of the main branch.
For example, this is the logic I have in my config that I would like to use this plugin for:
```lua
      function()
        local url = vim.fn.system("gh browse -n " .. vim.fn.expand("%") .. ":" .. vim.api.nvim_win_get_cursor(0)[1])
        vim.api.nvim_command("let @+ = '" .. url .. "'")
        vim.notify(url)
      end,
```

WDYT?

**Comment by linrongbin16** [comment]
hi @dlvhdr,

do you mean always generate the `main`/`master` branch, or generate *the current branch* of the git repo?

**Comment by linrongbin16** [comment]
I submit a PR: https://github.com/linrongbin16/gitlinker.nvim/pull/152 which provide any user defined router type, e.g. `master_branch` router type.

I didn't provide the `_A.DEFAULT_BRANCH` component yet, but it's close.

**Comment by dlvhdr** [comment]
> hi @dlvhdr,
> 
> do you mean always generate the `main`/`master` branch, or generate _the current branch_ of the git repo?
> 

I actually have auto commands for both the current branch and the main branch. I also have an autocommand for the current commit.

**Comment by dlvhdr** [comment]
> I submit a PR: #152 which provide any user defined router type, e.g. `master_branch` router type. please see: https://github.com/linrongbin16/gitlinker.nvim/tree/feat-custom-routers#create-your-own-router-type
> 
> I didn't provide the `_A.DEFAULT_BRANCH` component yet, but it's close.

Thanks so much, this will be very helpful

**Comment by linrongbin16** [comment]
when you generate url on default/current branch, will you also check if the git commit is valid?

**Comment by linrongbin16** [comment]
hi @dlvhdr , I provide two more components `default_branch` and `current_branch` in #159 , which should help you generate the url with real-time detecting branch name.

**Comment by linrongbin16** [comment]
Decide to support default/current branch as a builtin ability.
