### ISSUE TITLE
File only url

### ISSUE THREAD

**Issue by lopi-py** [linrongbin16/gitlinker.nvim#180]
How can I get file only url? is it implemented?

**Comment by linrongbin16** [comment]
> How can I get file only url? is it implemented?

hi @lopi-py, do you mean the raw remote url? such as 'https://github.com/linrongbin16/gitlinker.nvim.git'?

**Comment by lopi-py** [comment]
@linrongbin16 No, I meant something like this https://github.com/linrongbin16/gitlinker.nvim/blob/585f902062c92bf9fc5135017a5c3c427f8ccfc5/README.md. No lines involved, just the file.

**Comment by linrongbin16** [comment]
> @linrongbin16 No, I meant something like this https://github.com/linrongbin16/gitlinker.nvim/blob/585f902062c92bf9fc5135017a5c3c427f8ccfc5/README.md. No lines involved, just the file.

emmmm, no, that will need customization.

**Comment by lopi-py** [comment]
Wdym? That would be really helpful. I find myself needing this.

**Comment by linrongbin16** [comment]
hi @lopi-py, you could take a look at below sections:

1. configuration: https://github.com/linrongbin16/gitlinker.nvim?tab=readme-ov-file#configuration
2. customization: https://github.com/linrongbin16/gitlinker.nvim?tab=readme-ov-file#fully-customize-urls

**Comment by lopi-py** [comment]
It sounds good, perhaps it wouldn't be bad as a built-in thing. Another option could be to do file only if the command is not called in visual mode, if its called un visual mode and a single line is selected, it could convert the range into that single line.

**Comment by linrongbin16** [comment]
hi @lopi-py,

we should not change behavior in normal mode, e.g. remove line number from `browse` router. just add new router `fileonly` or something.

it's possible to add new router type `fileonly`, it's just a little bit too much maintain work. there's 3～4 places need to modify.

if there are `n` git hosts (now it's 5), `m` routers (now it's 2), I will have to maintain `n * m` things. most of them are duplicate work.

**Comment by lopi-py** [comment]
Understandable 👍

**Comment by tvsfx** [comment]
> if there are n git hosts (now it's 5), m routers (now it's 2), I will have to maintain n * m things. most of them are duplicate work.

I was recently looking at the [code for routers](https://github.com/linrongbin16/gitlinker.nvim/blob/a221c13fc3c7f5b8799933f4966ee8e618287292/spec/gitlinker_spec.lua?plain=1#L18-L21) in `gitlinker`, and this `n * m` explosion stood out to me.

Couldn't you define a notion of `format`s, i.e. sets of remotes that have their URLs formatted the same way, that can then customize URLs based on the required use-case (e.g. current_branch, default_branch, blame, ...). This would reduce the amount of duplication in several ways:
* You can just pass in a table containing all the information required for the use case of interest and the current format (this is a visitor pattern in the most general case, but you might not need to differentiate on use case, since you don't need this right now either). You could then reuse most of the code for formatting -for example- `default_branch` vs. `current_branch`.
* You can easily support more use cases, for example whole-file references, since you can just have an extra switch to turn off line number generation. Hand-wavy example:
```lua
function github_format(parameters, use_case)
   local file_url = generate_url_without_line_numbers(parameters) -- follows current logic, e.g.: https://github.com/linrongbin16/gitlinker.nvim/blob/a221c13fc3c7f5b8799933f4966ee8e618287292/spec/gitlinker_spec.lua?plain=1#L47-L53
   local final_url = use_case == whole_file and file_url or append_lines_to_url(file_url, parameters)
end
```

**Comment by linrongbin16** [comment]
> Couldn't you define a notion of `format`s

I like the `format` term, just like every git host can have their own display method/function. For those custom git host, they need to define/implement their own method.

> i.e. sets of remotes that have their URLs formatted the same way

It sounds like a group of git hosts can use the same implementation of `format` function? If I understand this correctly, for example, many self-host github domain will use name `xxx.github.io`. So their permlinks will be almost the same, only the `host` part is different.

> You can just pass in a table containing all the information required for the use case of interest and the current format (this is a visitor pattern in the most general case, but you might not need to differentiate on use case, since you don't need this right now either). You could then reuse most of the code for formatting -for example- `default_branch` vs. `current_branch`.

emmm, actually in my practice, I found the "string template" is a much better way to help users generate/customize their own git hosts. Compared with lua function, it reduces a lot of hand writing lua code. Please see: https://github.com/linrongbin16/gitlinker.nvim?tab=readme-ov-file#string-template

At last, maybe I was kind of arbitrarily that I refused such requirements. At that time, I am just afraid there will be more and more type of routers. But now, I think there will not be so many types, and "file only" could be accepted as a built-in type of routers.

**Comment by tvsfx** [comment]
> It sounds like a group of git hosts can use the same implementation of format function? If I understand this correctly, for example, many self-host github domain will use name xxx.github.io. So their permlinks will be almost the same, only the host part is different. But, to category those git hosts needs more investigation, this plugin now simply use regex-based (in lua, it's called "lua pattern") key-value hash map to map from a git host to its rule of generating the permlinks.

Yes, I think you can keep the pattern-matching on URLs the same, but just assign formats to those URLs. Then when a user wants to add/overwrite some variant, they can just add a pattern-format mapping from `xxx.github.io` to `GithubFormat`, which defines the parsing.

> emmm, actually in my practice, I found the "string template" is a much better way to help users generate/customize their own git hosts. Compared with lua function, it reduces a lot of hand writing lua code. Please see: https://github.com/linrongbin16/gitlinker.nvim?tab=readme-ov-file#string-template

Right, I can see how that'd be convenient for users. Although I'd think that if `parameters` in my pseudocode above contained the same `_A.*` values you allow as fields, that it's not much more difficult to just write lua code. I think format strings might get annoying if you have to merge many formatters, but that'd be to be seen.

In any case, you could do the classical neovim thing where e.g. `github_format` above either returns a format string directly (current situation) or a function that returns said string, given some arguments (new proposal, where you can still choose to use format parameters or just pass a table in like I did above).
