### ISSUE TITLE
Async api

### ISSUE THREAD

**Issue by lopi-py** [linrongbin16/gitlinker.nvim#181]
The title says it. It is quite annoying to have the editor to freeze for a second, an async managed api would improve the ux a lot. If you are open to this, I could try to make a PR.

**Comment by linrongbin16** [comment]
> The title says it. It is quite annoying to have the editor to freeze for a second, an async managed api would improve the ux a lot. If you are open to this, I could try to make a PR.

hi @lopi-py, do you mean, the 'GitLink' command running without blocking? e.g. don't wait for those git commands finishing?

**Comment by lopi-py** [comment]
@linrongbin16 Ok, would you mind if I use [plenary.nvim](https://github.com/nvim-lua/plenary.nvim) for async (and maybe other) utilities? or do you want to keep this plugin dependency-free? I think plenary.nvim is one of that plugins that every neovim user has installed lol.

**Comment by linrongbin16** [comment]
> @linrongbin16 Ok, would you mind if I use [plenary.nvim](https://github.com/nvim-lua/plenary.nvim) for async (and maybe other) utilities? or do you want to keep this plugin dependency-free? I think plenary.nvim is one of that plugins that every neovim user has installed lol.

emmmm, in early days when I just forked this plugin, it's depend on plenary. but the path seems not working correctly on Windows, so I  replaced it with another library I written myself: https://github.com/linrongbin16/commons.nvim.

could you tell me which component are you going to need in plenary?

**Comment by lopi-py** [comment]
> could you tell me which component are you going to need in plenary?

https://github.com/nvim-lua/plenary.nvim/blob/master/lua/plenary/async/init.lua
and maybe https://github.com/nvim-lua/plenary.nvim/blob/master/lua/plenary/job.lua

**Comment by linrongbin16** [comment]
> > could you tell me which component are you going to need in plenary?
> 
> https://github.com/nvim-lua/plenary.nvim/blob/master/lua/plenary/async/init.lua and maybe https://github.com/nvim-lua/plenary.nvim/blob/master/lua/plenary/job.lua

the commons don't have this async component. It will have to pass callbacks when running something async.

**Comment by lopi-py** [comment]
Well, plenary works fine for me. I use it on Windows with no issues. We could take https://github.com/ms-jpq/lua-async-await as reference.

**Comment by linrongbin16** [comment]
> Well, plenary works fine for me. I use it on Windows with no issues. We could take https://github.com/ms-jpq/lua-async-await as reference.

it looks good, single file is much easier to embed into the commons library directly.

**Comment by linrongbin16** [comment]
I also found below coroutine/async library for Neovim:

https://github.com/yutkat/my-neovim-pluginlist/blob/6793d2e4e2456cba03d17d9352f918a2804ad863/neovim-lua-library.md?plain=1#L68-L79

They look great:

```markdown
## async

- [nvim-lua/plenary.nvim(async)](https://github.com/nvim-lua/plenary.nvim) ![](https://img.shields.io/github/stars/nvim-lua/plenary.nvim) ![](https://img.shields.io/github/last-commit/nvim-lua/plenary.nvim) ![](https://img.shields.io/github/commit-activity/y/nvim-lua/plenary.nvim)
- [ms-jpq/lua-async-await](https://github.com/ms-jpq/lua-async-await) ![](https://img.shields.io/github/stars/ms-jpq/lua-async-await) ![](https://img.shields.io/github/last-commit/ms-jpq/lua-async-await) ![](https://img.shields.io/github/commit-activity/y/ms-jpq/lua-async-await)
- [notomo/promise.nvim](https://github.com/notomo/promise.nvim) ![](https://img.shields.io/github/stars/notomo/promise.nvim) ![](https://img.shields.io/github/last-commit/notomo/promise.nvim) ![](https://img.shields.io/github/commit-activity/y/notomo/promise.nvim)
- [iamcco/async-await.lua](https://github.com/iamcco/async-await.lua) ![](https://img.shields.io/github/stars/iamcco/async-await.lua) ![](https://img.shields.io/github/last-commit/iamcco/async-await.lua) ![](https://img.shields.io/github/commit-activity/y/iamcco/async-await.lua)
- [kevinhwang91/promise-async](https://github.com/kevinhwang91/promise-async) ![](https://img.shields.io/github/stars/kevinhwang91/promise-async) ![](https://img.shields.io/github/last-commit/kevinhwang91/promise-async) ![](https://img.shields.io/github/commit-activity/y/kevinhwang91/promise-async)
- [lewis6991/async.nvim](https://github.com/lewis6991/async.nvim) ![](https://img.shields.io/github/stars/lewis6991/async.nvim) ![](https://img.shields.io/github/last-commit/lewis6991/async.nvim) ![](https://img.shields.io/github/commit-activity/y/lewis6991/async.nvim)
- [ec965/async-uv.nvim](https://github.com/ec965/async-uv.nvim) ![](https://img.shields.io/github/stars/ec965/async-uv.nvim) ![](https://img.shields.io/github/last-commit/ec965/async-uv.nvim) ![](https://img.shields.io/github/commit-activity/y/ec965/async-uv.nvim)
- [willothy/micro-async.nvim](https://github.com/willothy/micro-async.nvim) ![](https://img.shields.io/github/stars/willothy/micro-async.nvim) ![](https://img.shields.io/github/last-commit/willothy/micro-async.nvim) ![](https://img.shields.io/github/commit-activity/y/willothy/micro-async.nvim)
- [svermeulen/nvim-lusc](https://github.com/svermeulen/nvim-lusc) ![](https://img.shields.io/github/stars/svermeulen/nvim-lusc) ![](https://img.shields.io/github/last-commit/svermeulen/nvim-lusc) ![](https://img.shields.io/github/commit-activity/y/svermeulen/nvim-lusc)
- [nvim-neotest/nvim-nio](https://github.com/nvim-neotest/nvim-nio) ![](https://img.shields.io/github/stars/nvim-neotest/nvim-nio) ![](https://img.shields.io/github/last-commit/nvim-neotest/nvim-nio) ![](https://img.shields.io/github/commit-activity/y/nvim-neotest/nvim-nio)
```

**Comment by linrongbin16** [comment]
> Well, plenary works fine for me. I use it on Windows with no issues. We could take https://github.com/ms-jpq/lua-async-await as reference.

maybe it's just I'm not familiar with plenary API, so I made mistakes... it could be...

**Comment by lopi-py** [comment]
That won't work. Its spawning a new thread, which won't take upvalues and we can't pass table as arguments, so we can't share data. This is async work, not multithreading work. In the neovim world, non-blocking = async

**Comment by linrongbin16** [comment]
> That won't work. Its spawning a new thread, which won't take upvalues and we can't pass table as arguments, so we can't share data. This is async work, not multithreading work (also iirrc there is no actual multithreading in neovim). In the neovim world, non-blocking = async

So you do mean, the `new_work` cannot do function closure (e.g. capture the context/variables in lua runtime), only allow passing very limited primitive values (string/integer/boolean/etc) as arguments, correct?

**Comment by lopi-py** [comment]
Yep

**Comment by lopi-py** [comment]
Let's just do async, thats what all the other plugins do.

**Comment by linrongbin16** [comment]
> Let's just do async, thats what all the other plugins do.

agree

**Comment by linrongbin16** [comment]
For now the plugin is doing below steps when people type `:GitLink browse`:

1. parse the command line arguments to get the router `browse`, also get the visual selected line numbers. see: 
 
 
 https://github.com/linrongbin16/gitlinker.nvim/blob/585f902062c92bf9fc5135017a5c3c427f8ccfc5/lua/gitlinker.lua?plain=1#L524-L552

**Comment by lopi-py** [comment]
I have to admit that I ended up using https://github.com/lewis6991/async.nvim as embedded. It's pretty good.

**Comment by linrongbin16** [comment]
sure, they are both very good Neovim experts.

**Comment by lopi-py** [comment]
That would conflict I think, because I'm using lewis's async

**Comment by linrongbin16** [comment]
emmm, maybe 

> That would conflict I think, because I'm using lewis's async

maybe first copy the single file to this project as 'gitlinker.async' module, and use it in other places.

I need to compare these two library, see which one is better.

**Comment by lopi-py** [comment]
Ok, I'll add it into gitlinker.async. So you decide what to do

**Comment by lopi-py** [comment]
Got it working, just a final touches.

**Comment by linrongbin16** [comment]
> Got it working, just some final touches.

if the PR works, let's just use it in this plugin. It's ok. We don't have to choose 'lua-async-await' library, if there's no other issues or requirements.
