### ISSUE TITLE
URL Parsing Failure Issue

### ISSUE THREAD

**Issue by linrongbin16** [linrongbin16/gitlinker.nvim#193]
There are many people had the internal url parsing exception, which is because of missing use cases.

Please add your use cases here.

Three things are needed:
1. The output of `git remote get-url origin`.
2. The expected git host url example.
3. The `router` config you will use to make it work.

**Comment by linrongbin16** [comment]
# builtin `http`/`https` protocol

### case-1 https://github.com/linrongbin16/gitlinker.nvim

1. git remote config output: `https://github.com/linrongbin16/gitlinker.nvim.git`
2. expected git host url: `https://github.com/linrongbin16/gitlinker.nvim/blob/c5a4bdd78f3dab3c6017a3b56932b334b94f55c6/.github/ISSUE_TEMPLATE/bug.md?plain=1#L10`
3. `router` configuration: default config

**Comment by linrongbin16** [comment]
I think need a more professional library to parse git remote url instead of handle writing parser.

**Comment by skoch13** [comment]
@linrongbin16 correct, mine is set to ssh://git@git.xxx.yyy/%PROJECT_KEY%/%REPO%.git

**Comment by linrongbin16** [comment]
> @linrongbin16 correct, mine is set to `ssh://git@git.xxx.yyy/%PROJECT_KEY%/%REPO%.git`

thanks!
