### ISSUE TITLE
FeatureRequest: generate link for a PR

### ISSUE THREAD

**Issue by linrongbin16** [linrongbin16/gitlinker.nvim#206]
discussion at: https://github.com/ruifm/gitlinker.nvim/issues/91#issuecomment-1953050496

**Comment by linrongbin16** [comment]
don't know how to do it.

**Comment by Diaoul** [comment]
A dumb implementation (but maybe good enough) would be to grab the PR number from the commit message on the line blame.

e.g. for [this commit](https://github.com/linrongbin16/gitlinker.nvim/commit/944a4b84266712bc4d48bafcaf5054e342b89fa1)
```
docs(usage): fold api section (https://github.com/linrongbin16/gitlinker.nvim/pull/219)
```

**Comment by linrongbin16** [comment]
> A dumb implementation (but maybe good enough) would be to grab the PR number from the commit message on the line blame.
> 
> e.g. for [this commit](https://github.com/linrongbin16/gitlinker.nvim/commit/944a4b84266712bc4d48bafcaf5054e342b89fa1)
> 
> ```
> docs(usage): fold api section (#219)
> ```
> 
> -> PR is #219

I'm using squash merge & conventional commits, so the `docs(usage): fold api section (#219)` is not a standardized message generated by GitHub.

I did some search and found this one: https://stackoverflow.com/a/25914885/4438921.

The small text `master (#219)` should be a standardized message generated by GitHub.

![image](https://github.com/linrongbin16/gitlinker.nvim/assets/6496887/2f9e40a6-8914-4f53-b664-eac243417175)

**Comment by Diaoul** [comment]
Yes I know, it would only work in this case. Although, that's still something interesting for the users of this workflow.
