### ISSUE TITLE
Bug: Encode spaces in url

### ISSUE THREAD

**Issue by linrongbin16** [linrongbin16/gitlinker.nvim#224]
Discussion: https://github.com/ruifm/gitlinker.nvim/issues/104.

1. What's the output of `git remote get-url origin`?

   It's ...

2. what's the expect git host url you want to generate?

   It's ...

3. how do you configure this plugin?

   It's ...

**Comment by joshmedeski** [comment]
I don't think this is much work. Do you want me to create a PR?

**Comment by linrongbin16** [comment]
> I don't think this is much work. Do you want me to create a PR?

hi @joshmedeski , welcome !

**Comment by joshmedeski** [comment]
It does not work for my use case.

I prefer to yank and directly paste it in a messaging app (to coworkers or friends), and those programs (Discord and Apple Messages) can't encode the value on paste.

**Comment by linrongbin16** [comment]
hi @joshmedeski ,

This issue is fixed in #226 , please pull master branch and have a try.

**Comment by joshmedeski** [comment]
Yes, thank you so much! 🎉
