### ISSUE TITLE
Question: current_branch and default_branch for custom domains

### ISSUE THREAD

**Issue by achojo** [linrongbin16/gitlinker.nvim#244]
Hi, I just started to use gitlinker.nvim and I liked it a lot.

I have configured `browse` and `blame` for custom Gitlab domain

This is the how it's looks like (just domain is changed)
```lua
require('gitlinker').setup({
  router = {
    browse = {
      ["^gitlab%.your%.host"] = require('gitlinker.routers').gitlab_browse,
    },
    blame = {
      ["^gitlab%.your%.host"] = require('gitlinker.routers').gitlab_blame,
    },
  }
})
```

And wanted to ask, is there a way to add `current_branch` and `default_branch` for custom domains with builtin functions?

**Comment by linrongbin16** [comment]
hi @achojo , no.

The API is a legacy design before the string template.

So I didn't implement APIs for the branches.

Please try string template, or PR is welcome as well.

**Comment by achojo** [comment]
Thanks for response, I think I am going to start using string templates.

And just want to leave a link to the file where builtin string templates reside for anyone who will be looking for it.
https://github.com/linrongbin16/gitlinker.nvim/blob/542f51784f20107ef9ecdadc47825204837efed5/lua/gitlinker/configs.lua?plain=1#L20

Kind of small contribution :)
